services:
  cashflow_app:
    networks:
      - web
    container_name: cashflow_app
    build:
      context: ../cashflow_app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ../cashflow_app/go.mod:/var/www/cashflow_app/go.mod
      - ../cashflow_app:/var/www/cashflow_app
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: go run cmd/app/main.go

  pg:
    networks:
      - web
    container_name: cashflow_pg
    build:
      context: services/pg
    env_file:
      - services/pg/env/base.env
      - services/pg/env/extended.env
    environment:
      - PORT=${PG_PORT}
    command: postgres -c log_statement=all
    working_dir: /var/www/pg
    volumes:
      - ./services/pg/data:/var/lib/pgsql/data:cached
      - ./services/pg/cashflow_db_check.sh:/tmp/cashflow_db_check.sh
      - ./services/pg/cashflow_healthcheck.sh:/tmp/cashflow_healthcheck.sh
    ports:
      - ${PG_PORT}:${PG_PORT}

networks:
  web:
    driver: bridge

volumes:
  shared_volume: {}
